version: "3.9"
services:
  api:
    build: .
    image: send-message:latest
    container_name: send-message
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - JAVA_OPTS=${JAVA_OPTS:-}
      # Optionally set one of below in .env to enable JWT validation against external issuer
      # SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      # SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
    restart: unless-stopped 