server:
  port: 8080

spring:
  application:
    name: send-message
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:}

slack:
  bot-token: ${SLACK_BOT_TOKEN:}
  api-base-url: ${SLACK_API_BASE_URL:https://slack.com/api}

security:
  api-key: ${API_KEY:}

resilience4j:
  ratelimiter:
    configs:
      base:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 1s
    instances:
      slack-bot:
        base-config: base
  circuitbreaker:
    configs:
      base:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 50
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
    instances:
      slack-bot:
        base-config: base

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO 